#端口的设置
server:
  port: 8080
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring:
    #sqlserver的配置
    datasource:
        url: jdbc:sqlserver://192.168.0.125:1433;DatabaseName=custom
        username: sa
        password: sdgl#123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #elasticsearch的配置
    data:
      elasticsearch:
          cluster-name:  elasticsearch #默认为elasticsearch
          cluster-nodes: 127.0.0.1:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
          properties:
              path:
                logs: ./elasticsearch/log #elasticsearch日志存储目录
                data: ./elasticsearch/data #elasticsearch数据存储目录
#redis的配置
jedis:
    host: 192.168.0.125
    port: 6379
    password:
    pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大和最小空闲连接
        max-idle: 8
        min-idle: 0
        max-wait: 1000
        timeout: 0
    database: 0

#mybatis的配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.holyrobot.bean

#pagehelper分页插件
pagehelper:
    helperDialect: sqlserver
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql









